name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: platforms;android-28
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'  # 替换为您所需的Flutter版本
    - name: Install dependencies
      run: cd ./flutter && flutter pub get

    

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
    
    - name: Run tests
      run: cd ./flutter && flutter test
      
    - run: cd ./flutter/android/ 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
